import { Injectable } from '@angular/core';
import { Game } from '../model/game'

@Injectable({
  providedIn: 'root'
})
export class GameService {
  private games = new Array<Game>();
  private autoGeneratedId = 0;

  constructor() { }

  insert(game: Game):void{
    game.id = this.autoGeneratedId;
    this.games.push(game);
    this.autoGeneratedId++;
  }

  list(): Array<Game> {
    return this.games;
  }

  update(game: Game):void {
    const i = this.games.findIndex(g => g.id === game.id);

    if(i>=0){
      this.games[i] = game;
    }
  }

  remove(id:number):void{
    this.games = this.games.filter((game)=> {
       return game.id !== id;
    });
  }

  // remove(id: number): void{

  //   for(let i = 0; this.games.length;i++){
  //     const g = this.games[i];
  //     if(id === g.id){
  //       this.games.splice(i, 1);
  //       break;
  //     }
  //   }
  // }

  // remove(id:number): void{
  //   this.games.forEach((game, i) => {
  //     if(id === g.id){
  //       this.games.splice(i, 1)
  //     }
  //   });
  // }


  // update2(game: Game): void{
  //   this.games.forEach((g, i) => {
  //     if(game.id === g.id){
  //       this.games[i] = game
  //     }
  //   });
  // }

}
